#!/usr/bin/env python3
# Build the comprehensive multifloats vs boost op matrix from the four
# harnesses' textual reports. Reads /tmp/{mf,bd}_{fuzz,bench}.txt and
# emits Markdown to stdout, suitable for splicing into
# doc/developer/BOOST_OP_MATRIX.md.
#
# Run after:
#   ./build/cpp_fuzz       1000000 42 > /tmp/mf_fuzz.txt
#   ./build/boost_dd_fuzz  1000000 42 > /tmp/bd_fuzz.txt
#   ./build/cpp_bench                 > /tmp/mf_bench.txt
#   ./build/boost_dd_bench            > /tmp/bd_bench.txt

import re
import sys


def load_fuzz(path):
    out = {}
    with open(path) as f:
        for line in f:
            m = re.match(r"^\s+(\S+)\s+(\d+)\s+([0-9.e+-]+)\s+([0-9.e+-]+)\s*$", line)
            if m:
                out[m.group(1)] = m.group(3)
    return out


def load_bench(path):
    out = {}
    with open(path) as f:
        in_table = False
        for line in f:
            if re.match(r"^\s+op\s", line):
                in_table = True
                continue
            if not in_table:
                continue
            m = re.match(
                r"^\s+(\S+)\s+(\d+)\s+([0-9.]+)\s+([0-9.]+)\s+([0-9.]+)x", line
            )
            if m:
                out[m.group(1)] = m.group(4)
    return out


mf_f = load_fuzz("/tmp/mf_fuzz.txt")
bd_f = load_fuzz("/tmp/bd_fuzz.txt")
mf_b = load_bench("/tmp/mf_bench.txt")
bd_b = load_bench("/tmp/bd_bench.txt")

# Aliases: report cell name → list of multifloats labels to try, list of boost labels.
# When mf/bd use different names for the same op, list both so the cell shows the
# matched value rather than two unrelated dashes.
ALIAS = {
    "fma":     (["fma_cxx", "fmadd"], ["fma"]),
    "tgamma":  (["gamma"],            ["tgamma"]),
    "lgamma":  (["lngamma"],          ["lgamma"]),
}


def fuzz_cell(side_dict, op, side):
    if op in ALIAS:
        names = ALIAS[op][0 if side == "mf" else 1]
        for n in names:
            if n in side_dict:
                return side_dict[n]
        return "—"
    return side_dict.get(op, "—")


def bench_cell(side_dict, op):
    return side_dict.get(op, "—")


CATEGORIES = [
    ("Arithmetic", [
        "add", "sub", "mul", "div", "sqrt", "cbrt", "fma",
        "abs", "neg", "add_fd", "mul_df",
    ]),
    ("Min / max / sign / distance", [
        "fmin", "fmax", "fdim", "copysign", "hypot", "min3", "max3", "sinks",
    ]),
    ("Modulo / remainder", [
        "fmod", "modulo", "remainder", "remquo",
    ]),
    ("Rounding", [
        "floor", "ceil", "trunc", "round", "nearbyint", "rint",
        "lround", "llround", "lrint", "llrint",
    ]),
    ("Scaling / exponent", [
        "ldexp", "scalbn", "scalbln", "logb", "ilogb",
        "frexp.frac", "frexp.exp", "modf.frac", "modf.int",
    ]),
    ("Linear / misc", [
        "lerp",
    ]),
    ("exp / log", [
        "exp", "exp2", "expm1", "log", "log2", "log10", "log1p",
    ]),
    ("pow", [
        "pow", "pow_md", "pow_dm", "pow_int",
    ]),
    ("Trig (radian)", [
        "sin", "cos", "tan", "sincos", "sincos_s", "sincos_c",
        "asin", "acos", "atan", "atan2",
    ]),
    ("Trig (π-scaled)", [
        "sinpi", "cospi", "tanpi",
        "asinpi", "acospi", "atanpi", "atan2pi",
    ]),
    ("Hyperbolic", [
        "sinh", "cosh", "tanh", "sinhcosh", "sinhcosh_s", "sinhcosh_c",
        "asinh", "acosh", "atanh",
    ]),
    ("Special: erf / gamma", [
        "erf", "erfc", "erfcx", "tgamma", "lgamma",
    ]),
    ("Bessel", [
        "bj0", "bj1", "bjn", "by0", "by1", "byn", "jn_range", "yn_range",
    ]),
]

# Complex pairs: stem name → (mf has it, bd has it). All multifloats only.
COMPLEX_STEMS = [
    "cadd", "csub", "cmul", "cdiv", "cconjg", "cproj",
    "csqrt", "cexp", "cexpm1",
    "clog", "clog1p", "clog2", "clog10",
    "cpow",
    "csin", "ccos", "ctan",
    "csinh", "ccosh", "ctanh",
    "casin", "cacos", "catan",
    "casinh", "cacosh", "catanh",
    "csinpi", "ccospi",
]

# cdd_* bench-only labels (no fuzz row in either side).
CDD_BENCH = [
    "cdd_add", "cdd_sub", "cdd_mul", "cdd_div",
    "cdd_abs", "cdd_arg", "cdd_conjg", "cdd_proj",
    "cdd_sqrt", "cdd_exp", "cdd_expm1",
    "cdd_log", "cdd_log1p", "cdd_log2", "cdd_log10",
    "cdd_pow",
    "cdd_sin", "cdd_cos", "cdd_tan",
    "cdd_sinh", "cdd_cosh", "cdd_tanh",
    "cdd_asin", "cdd_acos", "cdd_atan",
    "cdd_asinh", "cdd_atanh",
    "cdd_sinpi", "cdd_cospi",
]


def emit_table(rows):
    print("| op | mf max_rel | boost max_rel | mf time [s] | boost time [s] |")
    print("|---|---|---|---|---|")
    for r in rows:
        print("| " + " | ".join(r) + " |")
    print()


print("# multifloats vs Boost.Multiprecision — operation matrix")
print()
print("Generated by `scripts/build_op_matrix.py`. One row per operation that")
print("either side implements; a `—` cell means that side does not implement")
print("the op or the harness does not test/time it. `mf`/`boost` time columns")
print("are wall-clock seconds on the same workload (lower is better).")
print()
print("Source data: `cpp_fuzz 1000000 42`, `boost_dd_fuzz 1000000 42`,")
print("`cpp_bench`, `boost_dd_bench` (all matched seed). Re-generate with:")
print()
print("```sh")
print("cmake -DBUILD_TESTING=ON -DMULTIFLOATS_BUILD_BENCH=ON \\")
print("      -DMULTIFLOATS_BUILD_BOOST_COMPARE=ON -S . -B build")
print("cmake --build build -j --target cpp_fuzz cpp_bench boost_dd_fuzz boost_dd_bench")
print("./build/cpp_fuzz       1000000 42 > /tmp/mf_fuzz.txt")
print("./build/boost_dd_fuzz  1000000 42 > /tmp/bd_fuzz.txt")
print("./build/cpp_bench                  > /tmp/mf_bench.txt")
print("./build/boost_dd_bench             > /tmp/bd_bench.txt")
print("python3 scripts/build_op_matrix.py > doc/developer/BOOST_OP_MATRIX.md")
print("```")
print()
print("Boost's `cpp_double_double` backend natively implements only")
print("`+ − × ÷ sqrt fabs exp log pow floor ceil frexp ldexp ilogb`;")
print("everything else routes through `boost::math::*` generics on top of")
print("the backend, which explains the boost-side precision/speed gaps in")
print("the trig / hyperbolic / Bessel sections.")
print()
print("Naming notes:")
print("- multifloats labels its FMA fuzz row `fma_cxx`/`fmadd`; boost uses")
print("  `fma`. Reported below as a single `fma` row.")
print("- multifloats fuzzes `gamma`/`lngamma` labels for what boost calls")
print("  `tgamma`/`lgamma`. Merged for readability.")
print("- multifloats `sincos`/`sinhcosh` produce two stat rows (`_s` sin")
print("  component and `_c` cos component); the bench measures the joint")
print("  call. Both shown.")
print()

for cat, ops in CATEGORIES:
    print(f"## {cat}")
    print()
    rows = []
    for op in ops:
        mfr = fuzz_cell(mf_f, op, "mf")
        bdr = fuzz_cell(bd_f, op, "bd")
        mft = bench_cell(mf_b, op)
        bdt = bench_cell(bd_b, op)
        if mfr == "—" and bdr == "—" and mft == "—" and bdt == "—":
            continue
        rows.append([op, mfr, bdr, mft, bdt])
    if rows:
        emit_table(rows)
    else:
        print("(no rows recorded on either side)\n")

# Complex (multifloats only — boost's cpp_double_double has no native
# complex). Show two columns per row: real and imaginary component.
print("## Complex (multifloats only — boost has no native complex backend)")
print()
print("Real / imag components reported as two rows per stem; bench is the")
print("packed-complex `cdd_*` C-ABI surface, no per-component split.")
print()
print("### Complex fuzz (re / im rel-err)")
print()
print("| op | mf re max_rel | mf im max_rel |")
print("|---|---|---|")
for stem in COMPLEX_STEMS:
    re_v = mf_f.get(stem + "_re", "—")
    im_v = mf_f.get(stem + "_im", "—")
    if re_v == "—" and im_v == "—":
        continue
    print(f"| {stem} | {re_v} | {im_v} |")
print()

# cabs/carg are scalar-out (one row each) — already in the main fuzz tables?
# They live in mf_f as 'cabs'/'carg'. Show them in their own row so the table
# is exhaustive.
extras = [(o, mf_f.get(o, "—")) for o in ("cabs", "carg")]
extras = [(o, v) for (o, v) in extras if v != "—"]
if extras:
    print("Scalar-out complex ops:")
    print()
    print("| op | mf max_rel |")
    print("|---|---|")
    for o, v in extras:
        print(f"| {o} | {v} |")
    print()

print("### Complex bench (cdd_* C-ABI surface, packed)")
print()
print("| op | mf time [s] |")
print("|---|---|")
for stem in CDD_BENCH:
    v = mf_b.get(stem, "—")
    if v == "—":
        continue
    print(f"| {stem} | {v} |")
print()

# Footer: counts
def count(d):  return sum(1 for v in d.values() if v not in ("—", None))
print("---")
print()
print("Counts: "
      f"mf fuzz {count(mf_f)} ops, "
      f"boost fuzz {count(bd_f)} ops, "
      f"mf bench {count(mf_b)} ops, "
      f"boost bench {count(bd_b)} ops.")
